// <auto-generated />
namespace DotNet_05.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddFollowingAndFollowers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFollowingAndFollowers));
        
        string IMigrationMetadata.Id
        {
            get { return "201906040516017_AddFollowingAndFollowers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
